// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mpc "github.com/macrowallets/waas/app/services/mpc"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Keygen provides a mock function with given fields: ctx, curve
func (_m *MockService) Keygen(ctx context.Context, curve mpc.Curve) (*mpc.KeygenResult, error) {
	ret := _m.Called(ctx, curve)

	if len(ret) == 0 {
		panic("no return value specified for Keygen")
	}

	var r0 *mpc.KeygenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mpc.Curve) (*mpc.KeygenResult, error)); ok {
		return rf(ctx, curve)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mpc.Curve) *mpc.KeygenResult); ok {
		r0 = rf(ctx, curve)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mpc.KeygenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, mpc.Curve) error); ok {
		r1 = rf(ctx, curve)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Keygen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keygen'
type MockService_Keygen_Call struct {
	*mock.Call
}

// Keygen is a helper method to define mock.On call
//   - ctx context.Context
//   - curve mpc.Curve
func (_e *MockService_Expecter) Keygen(ctx interface{}, curve interface{}) *MockService_Keygen_Call {
	return &MockService_Keygen_Call{Call: _e.mock.On("Keygen", ctx, curve)}
}

func (_c *MockService_Keygen_Call) Run(run func(ctx context.Context, curve mpc.Curve)) *MockService_Keygen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mpc.Curve))
	})
	return _c
}

func (_c *MockService_Keygen_Call) Return(_a0 *mpc.KeygenResult, _a1 error) *MockService_Keygen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Keygen_Call) RunAndReturn(run func(context.Context, mpc.Curve) (*mpc.KeygenResult, error)) *MockService_Keygen_Call {
	_c.Call.Return(run)
	return _c
}

// ReconstructEd25519PrivateKey provides a mock function with given fields: shareA, shareB
func (_m *MockService) ReconstructEd25519PrivateKey(shareA []byte, shareB []byte) ([]byte, error) {
	ret := _m.Called(shareA, shareB)

	if len(ret) == 0 {
		panic("no return value specified for ReconstructEd25519PrivateKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(shareA, shareB)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(shareA, shareB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(shareA, shareB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReconstructEd25519PrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconstructEd25519PrivateKey'
type MockService_ReconstructEd25519PrivateKey_Call struct {
	*mock.Call
}

// ReconstructEd25519PrivateKey is a helper method to define mock.On call
//   - shareA []byte
//   - shareB []byte
func (_e *MockService_Expecter) ReconstructEd25519PrivateKey(shareA interface{}, shareB interface{}) *MockService_ReconstructEd25519PrivateKey_Call {
	return &MockService_ReconstructEd25519PrivateKey_Call{Call: _e.mock.On("ReconstructEd25519PrivateKey", shareA, shareB)}
}

func (_c *MockService_ReconstructEd25519PrivateKey_Call) Run(run func(shareA []byte, shareB []byte)) *MockService_ReconstructEd25519PrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockService_ReconstructEd25519PrivateKey_Call) Return(_a0 []byte, _a1 error) *MockService_ReconstructEd25519PrivateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ReconstructEd25519PrivateKey_Call) RunAndReturn(run func([]byte, []byte) ([]byte, error)) *MockService_ReconstructEd25519PrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// ReconstructEd25519Scalar provides a mock function with given fields: shareA, shareB
func (_m *MockService) ReconstructEd25519Scalar(shareA []byte, shareB []byte) ([]byte, error) {
	ret := _m.Called(shareA, shareB)

	if len(ret) == 0 {
		panic("no return value specified for ReconstructEd25519Scalar")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(shareA, shareB)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(shareA, shareB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(shareA, shareB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReconstructEd25519Scalar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconstructEd25519Scalar'
type MockService_ReconstructEd25519Scalar_Call struct {
	*mock.Call
}

// ReconstructEd25519Scalar is a helper method to define mock.On call
//   - shareA []byte
//   - shareB []byte
func (_e *MockService_Expecter) ReconstructEd25519Scalar(shareA interface{}, shareB interface{}) *MockService_ReconstructEd25519Scalar_Call {
	return &MockService_ReconstructEd25519Scalar_Call{Call: _e.mock.On("ReconstructEd25519Scalar", shareA, shareB)}
}

func (_c *MockService_ReconstructEd25519Scalar_Call) Run(run func(shareA []byte, shareB []byte)) *MockService_ReconstructEd25519Scalar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockService_ReconstructEd25519Scalar_Call) Return(_a0 []byte, _a1 error) *MockService_ReconstructEd25519Scalar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ReconstructEd25519Scalar_Call) RunAndReturn(run func([]byte, []byte) ([]byte, error)) *MockService_ReconstructEd25519Scalar_Call {
	_c.Call.Return(run)
	return _c
}

// ReconstructSecp256k1PrivateKey provides a mock function with given fields: shareA, shareB
func (_m *MockService) ReconstructSecp256k1PrivateKey(shareA []byte, shareB []byte) ([]byte, error) {
	ret := _m.Called(shareA, shareB)

	if len(ret) == 0 {
		panic("no return value specified for ReconstructSecp256k1PrivateKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(shareA, shareB)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(shareA, shareB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(shareA, shareB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReconstructSecp256k1PrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconstructSecp256k1PrivateKey'
type MockService_ReconstructSecp256k1PrivateKey_Call struct {
	*mock.Call
}

// ReconstructSecp256k1PrivateKey is a helper method to define mock.On call
//   - shareA []byte
//   - shareB []byte
func (_e *MockService_Expecter) ReconstructSecp256k1PrivateKey(shareA interface{}, shareB interface{}) *MockService_ReconstructSecp256k1PrivateKey_Call {
	return &MockService_ReconstructSecp256k1PrivateKey_Call{Call: _e.mock.On("ReconstructSecp256k1PrivateKey", shareA, shareB)}
}

func (_c *MockService_ReconstructSecp256k1PrivateKey_Call) Run(run func(shareA []byte, shareB []byte)) *MockService_ReconstructSecp256k1PrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockService_ReconstructSecp256k1PrivateKey_Call) Return(_a0 []byte, _a1 error) *MockService_ReconstructSecp256k1PrivateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ReconstructSecp256k1PrivateKey_Call) RunAndReturn(run func([]byte, []byte) ([]byte, error)) *MockService_ReconstructSecp256k1PrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function with given fields: ctx, curve, shareA, shareB, inputs
func (_m *MockService) Sign(ctx context.Context, curve mpc.Curve, shareA []byte, shareB []byte, inputs mpc.SignInputs) ([]byte, error) {
	ret := _m.Called(ctx, curve, shareA, shareB, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mpc.Curve, []byte, []byte, mpc.SignInputs) ([]byte, error)); ok {
		return rf(ctx, curve, shareA, shareB, inputs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mpc.Curve, []byte, []byte, mpc.SignInputs) []byte); ok {
		r0 = rf(ctx, curve, shareA, shareB, inputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, mpc.Curve, []byte, []byte, mpc.SignInputs) error); ok {
		r1 = rf(ctx, curve, shareA, shareB, inputs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockService_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - curve mpc.Curve
//   - shareA []byte
//   - shareB []byte
//   - inputs mpc.SignInputs
func (_e *MockService_Expecter) Sign(ctx interface{}, curve interface{}, shareA interface{}, shareB interface{}, inputs interface{}) *MockService_Sign_Call {
	return &MockService_Sign_Call{Call: _e.mock.On("Sign", ctx, curve, shareA, shareB, inputs)}
}

func (_c *MockService_Sign_Call) Run(run func(ctx context.Context, curve mpc.Curve, shareA []byte, shareB []byte, inputs mpc.SignInputs)) *MockService_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mpc.Curve), args[2].([]byte), args[3].([]byte), args[4].(mpc.SignInputs))
	})
	return _c
}

func (_c *MockService_Sign_Call) Return(_a0 []byte, _a1 error) *MockService_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Sign_Call) RunAndReturn(run func(context.Context, mpc.Curve, []byte, []byte, mpc.SignInputs) ([]byte, error)) *MockService_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
