// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/macrowallets/waas/pkg/types"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// SendWebhook provides a mock function with given fields: ctx, msg
func (_m *MockSender) SendWebhook(ctx context.Context, msg types.WebhookMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.WebhookMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_SendWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWebhook'
type MockSender_SendWebhook_Call struct {
	*mock.Call
}

// SendWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - msg types.WebhookMessage
func (_e *MockSender_Expecter) SendWebhook(ctx interface{}, msg interface{}) *MockSender_SendWebhook_Call {
	return &MockSender_SendWebhook_Call{Call: _e.mock.On("SendWebhook", ctx, msg)}
}

func (_c *MockSender_SendWebhook_Call) Run(run func(ctx context.Context, msg types.WebhookMessage)) *MockSender_SendWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.WebhookMessage))
	})
	return _c
}

func (_c *MockSender_SendWebhook_Call) Return(_a0 error) *MockSender_SendWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_SendWebhook_Call) RunAndReturn(run func(context.Context, types.WebhookMessage) error) *MockSender_SendWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
