// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	types "github.com/macrowallets/waas/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockMPCSignatureFinalizer is an autogenerated mock type for the MPCSignatureFinalizer type
type MockMPCSignatureFinalizer struct {
	mock.Mock
}

type MockMPCSignatureFinalizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMPCSignatureFinalizer) EXPECT() *MockMPCSignatureFinalizer_Expecter {
	return &MockMPCSignatureFinalizer_Expecter{mock: &_m.Mock}
}

// FinalizeMPCSignature provides a mock function with given fields: unsigned, signature, publicKey
func (_m *MockMPCSignatureFinalizer) FinalizeMPCSignature(unsigned *types.UnsignedTx, signature []byte, publicKey []byte) (*types.SignedTx, error) {
	ret := _m.Called(unsigned, signature, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeMPCSignature")
	}

	var r0 *types.SignedTx
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.UnsignedTx, []byte, []byte) (*types.SignedTx, error)); ok {
		return rf(unsigned, signature, publicKey)
	}
	if rf, ok := ret.Get(0).(func(*types.UnsignedTx, []byte, []byte) *types.SignedTx); ok {
		r0 = rf(unsigned, signature, publicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.SignedTx)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.UnsignedTx, []byte, []byte) error); ok {
		r1 = rf(unsigned, signature, publicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMPCSignatureFinalizer_FinalizeMPCSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeMPCSignature'
type MockMPCSignatureFinalizer_FinalizeMPCSignature_Call struct {
	*mock.Call
}

// FinalizeMPCSignature is a helper method to define mock.On call
//   - unsigned *types.UnsignedTx
//   - signature []byte
//   - publicKey []byte
func (_e *MockMPCSignatureFinalizer_Expecter) FinalizeMPCSignature(unsigned interface{}, signature interface{}, publicKey interface{}) *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call {
	return &MockMPCSignatureFinalizer_FinalizeMPCSignature_Call{Call: _e.mock.On("FinalizeMPCSignature", unsigned, signature, publicKey)}
}

func (_c *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call) Run(run func(unsigned *types.UnsignedTx, signature []byte, publicKey []byte)) *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.UnsignedTx), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call) Return(_a0 *types.SignedTx, _a1 error) *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call) RunAndReturn(run func(*types.UnsignedTx, []byte, []byte) (*types.SignedTx, error)) *MockMPCSignatureFinalizer_FinalizeMPCSignature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMPCSignatureFinalizer creates a new instance of MockMPCSignatureFinalizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMPCSignatureFinalizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMPCSignatureFinalizer {
	mock := &MockMPCSignatureFinalizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
