// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/macrowallets/waas/pkg/types"
)

// MockL1DataFeeEstimator is an autogenerated mock type for the L1DataFeeEstimator type
type MockL1DataFeeEstimator struct {
	mock.Mock
}

type MockL1DataFeeEstimator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockL1DataFeeEstimator) EXPECT() *MockL1DataFeeEstimator_Expecter {
	return &MockL1DataFeeEstimator_Expecter{mock: &_m.Mock}
}

// EstimateL1DataFee provides a mock function with given fields: ctx, req
func (_m *MockL1DataFeeEstimator) EstimateL1DataFee(ctx context.Context, req types.TransferRequest) (*big.Int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EstimateL1DataFee")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.TransferRequest) (*big.Int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.TransferRequest) *big.Int); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.TransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockL1DataFeeEstimator_EstimateL1DataFee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateL1DataFee'
type MockL1DataFeeEstimator_EstimateL1DataFee_Call struct {
	*mock.Call
}

// EstimateL1DataFee is a helper method to define mock.On call
//   - ctx context.Context
//   - req types.TransferRequest
func (_e *MockL1DataFeeEstimator_Expecter) EstimateL1DataFee(ctx interface{}, req interface{}) *MockL1DataFeeEstimator_EstimateL1DataFee_Call {
	return &MockL1DataFeeEstimator_EstimateL1DataFee_Call{Call: _e.mock.On("EstimateL1DataFee", ctx, req)}
}

func (_c *MockL1DataFeeEstimator_EstimateL1DataFee_Call) Run(run func(ctx context.Context, req types.TransferRequest)) *MockL1DataFeeEstimator_EstimateL1DataFee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.TransferRequest))
	})
	return _c
}

func (_c *MockL1DataFeeEstimator_EstimateL1DataFee_Call) Return(_a0 *big.Int, _a1 error) *MockL1DataFeeEstimator_EstimateL1DataFee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockL1DataFeeEstimator_EstimateL1DataFee_Call) RunAndReturn(run func(context.Context, types.TransferRequest) (*big.Int, error)) *MockL1DataFeeEstimator_EstimateL1DataFee_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockL1DataFeeEstimator creates a new instance of MockL1DataFeeEstimator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockL1DataFeeEstimator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockL1DataFeeEstimator {
	mock := &MockL1DataFeeEstimator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
