// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/macrowallets/waas/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// MockTransferGasEstimator is an autogenerated mock type for the TransferGasEstimator type
type MockTransferGasEstimator struct {
	mock.Mock
}

type MockTransferGasEstimator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferGasEstimator) EXPECT() *MockTransferGasEstimator_Expecter {
	return &MockTransferGasEstimator_Expecter{mock: &_m.Mock}
}

// EstimateTransferGasLimit provides a mock function with given fields: ctx, req
func (_m *MockTransferGasEstimator) EstimateTransferGasLimit(ctx context.Context, req types.TransferRequest) (uint64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EstimateTransferGasLimit")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.TransferRequest) (uint64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.TransferRequest) uint64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.TransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferGasEstimator_EstimateTransferGasLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateTransferGasLimit'
type MockTransferGasEstimator_EstimateTransferGasLimit_Call struct {
	*mock.Call
}

// EstimateTransferGasLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - req types.TransferRequest
func (_e *MockTransferGasEstimator_Expecter) EstimateTransferGasLimit(ctx interface{}, req interface{}) *MockTransferGasEstimator_EstimateTransferGasLimit_Call {
	return &MockTransferGasEstimator_EstimateTransferGasLimit_Call{Call: _e.mock.On("EstimateTransferGasLimit", ctx, req)}
}

func (_c *MockTransferGasEstimator_EstimateTransferGasLimit_Call) Run(run func(ctx context.Context, req types.TransferRequest)) *MockTransferGasEstimator_EstimateTransferGasLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.TransferRequest))
	})
	return _c
}

func (_c *MockTransferGasEstimator_EstimateTransferGasLimit_Call) Return(_a0 uint64, _a1 error) *MockTransferGasEstimator_EstimateTransferGasLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferGasEstimator_EstimateTransferGasLimit_Call) RunAndReturn(run func(context.Context, types.TransferRequest) (uint64, error)) *MockTransferGasEstimator_EstimateTransferGasLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferGasEstimator creates a new instance of MockTransferGasEstimator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferGasEstimator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferGasEstimator {
	mock := &MockTransferGasEstimator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
